### ISSUE TITLE
Improve documentation with examples

### ISSUE THREAD

**Issue by kmelve** [netliferesearch/starter#15]
You should add configuration examples in the documentation, e.g. how to tweak browserSync, add another SCSS-library (e.g. Aleut.css) and so on.

**Comment by fredjens** [comment]
The Gulp setup including browserSync is [documented her]('https://github.com/netliferesearch/starter-gulp')

Adding other libaries is done as usual... 😄

**Comment by fredjens** [comment]
Hopefully better documentation for next version..
