### ISSUE TITLE
Markdown parsing errors on partials with parameters

### ISSUE THREAD

**Issue by nilsnh** [netliferesearch/starter#25]
Inside the markdown file I'm trying to do:

```html
{{>heyo param='Hello world' }}
```
with a `heyo.html` partial like so

```html
<div>
  {{param}}
</div>
```
Getting this error

```
[metalsmith-watch] ✓ Live reload server started on port: 35729
/home/nilsnh/Workspace-netlife/starter/metalsmith.js:68
    if (err) throw err;
             ^

Error: Parse error on line 4:
...param=’Hello world’ }}</div><h2 id="i
-----------------------^
Expecting 'EQUALS', got 'CLOSE'
```

**Comment by nilsnh** [comment]
Partials with parameters *do work* outside of markdown files btw.

**Comment by fredjens** [comment]
Partials in markdown with params only expect a field as input. [Added an example](https://github.com/netliferesearch/starter/blob/master/src/html/content/partials-markdown.md)
